sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ihor911/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ihor911/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-393952872961"
  bucket_path: "docker"
  on:
    branch: main
